
const SITE = {
  logo: "assets/images/logo.png",
  // --- Identité ---
  nom:      "Agencement Franques",
  slogan:   "Expert en Agencement Intérieur ", 
  baseline: "Spécialiste en agencement sur-mesure et menuiserie, je conçois vos espaces de vie — cuisines, salles de bain, rangements — et vos terrasses en bois. De la rénovation à la création, je transforme chaque mètre carré en un lieu d'exception.",
  copyright: `© ${new Date().getFullYear()} Agencement Franques`,

  // --- Contact ---
  telephone:     "06 72 13 05 20",
  telephoneHref: "tel:+33672130520",
  email:         "agencement.franques@orange.fr",
  emailHref:     "mailto:agencement.franques@orange.fr",
  adresse:       "Aveyron, France",

  legal: {
  proprietaire:  "Christophe Franques",
  siret:         "51203825800012",
  adresseLegale: "12340 Bezonnes, France",
  hebergeur:     "Vercel Inc., 340 Pine Street, San Francisco, CA 94104, USA",
  },
  // --- Réseaux sociaux ---
  instagram: "#",

  // --- Section "À propos" ---
  apropos: {
    titre:    "Mon histoire",
    photo: "assets/images/portrait.webp",
    textes: [
      `Plus de ${new Date().getFullYear() - 2009} ans de savoir-faire au service de vos projets.`,
      "Depuis 2009, j'accompagne mes clients pour transformer leurs rêves en réalisations concrètes. Menuisier de formation, j'ai bâti mon expertise sur le terrain, développant au fil des années une polyvalence qui me permet aujourd'hui de maîtriser chaque étape de votre agencement. Mon exigence reste la même : allier la passion du bois, la rénovation pour créer des lieux qui vous ressemblent."
    ],
  },
  // --- Expertises (carte compétences) ---
  expertises: [
    { categorie: "Second Œuvre",             label: "Rénovation Globale (Peinture, Placo, Plomberie)" },
    { categorie: "Extérieurs",               label: "Terrasse & Volets Roulants" },
    { categorie: "Conception",               label: "Mobilier Sur-Mesure" },
    { categorie: "Habitat & Pièces d'Eau",  label: "Cuisine & Salle de Bain" },

  ],

  // --- Portfolio ---
  portfolioCategories: ["Cuisine", "Pièces d'eau", "Menuiserie", "Mobilier", "Rénovation", "Extérieur"],

  projets: [
     {
      titre:       "Baie vitrée bois sur-mesure",
      description: "Menuiserie extérieure & Pose en charpente ancienne",
      type:        "Menuiserie",
      src: "assets/images/baie_vitree_bois.webp",
      alt: "Baie vitrée bois sur-mesure posée dans une ouverture en pierre",
    },
    {
      titre:       "Bibliothèque sur-mesure laquée",
      description: "Blanc laqué haute brillance & Rangements modulables",
      type:        "Mobilier",
      src: "assets/images/bibliotheque_sur_mesure_blanche.webp",
      alt: "Grande bibliothèque sur-mesure en blanc laqué avec portes, tiroirs et niches ouvertes",
    },
     {
      titre:       "Rénovation d'Eau",
      description: "Optimisation d'espace & Finitions haut de gamme",
      type:        "Pièces d'eau",
      src: "assets/images/douche.webp",
      alt: "Salle de bain rénovée avec carrelage texturé, douche à l'italienne et meuble vasque sur mesure",
    },
    {
      titre:       "Meuble TV cannage",
      description: "Bois chêne & Portes coulissantes cannage",
      type:        "Mobilier",
      src: "assets/images/meuble_tv_cannage.webp",
      alt: "Meuble TV bas en bois clair avec portes coulissantes en cannage naturel",
    },
   
    {
      titre:       "Carrelage pierre naturelle",
      description: "Pose en opus incertum & Joints en travertin",
      type:        "Rénovation",
      src: "assets/images/carrelage_pierre_naturelle.webp",
      alt: "Pose de carrelage en pierre naturelle dans une pièce aux murs en pierre apparente",
    },
    {
      titre:       "Double porte bois massif",
      description: "Menuiserie extérieure & Bois brut massif",
      type:        "Menuiserie",
      src: "assets/images/double_porte_bois.webp",
      alt: "Double porte d'entrée en bois massif brut avec imposte vitrée",
    },
    {
      titre:       "Terrasse bois & piscine",
      description: "Bois traité & Aménagement tour de piscine",
      type:        "Extérieur",
      src: "assets/images/terrasse_bois_piscine.webp",
      alt: "Terrasse en bois avec escalier et tour de piscine hors-sol intégré",
    },
    {
      titre:       "Cuisine Récente",
      description: "Agencement complet & Électroménager intégré",
      type:        "Cuisine",
      src: "assets/images/cuisine_récente.webp",
      alt: "Cuisine moderne avec îlot central, meubles blancs laqués et électroménager encastré",
    },  
    {
      titre:       "Terrasse extérieure",
      description: "Bois exotique & Aménagement paysager",
      type:        "Extérieur",
      src: "assets/images/terrace.webp",
      alt: "Grande terrasse en bois",
    },
    {
      titre:       "Escalier d'angle sur-mesure",
      description: "En bois",
      type:        "Menuiserie",
      src: "assets/images/escalier.webp",
      alt: "Escalier d'angle sur-mesure en bois",
    },
    {
      titre:       "Volet en bois sur-mesure",
      description: "",
      type:        "Menuiserie",
      src: "assets/images/volet.webp",
      alt: "Grand volet blanc en bois sur-mesure",
    },
    {
      titre:       "Porte en bois sur-mesure",
      description: "Bois massif & Finitions personnalisées",
      type:        "Menuiserie",
      src: "assets/images/porte_en_bois.webp",
      alt: "Porte en bois sur-mesure",
    },
    {
      titre:       "Table basse en bois avec une dalle en verre",
      description: "Bois travaillé à la main & Design unique avec une finition naturelle",
      type:        "Mobilier",
      src: "assets/images/table_basse.webp",
      alt: "Table basse en bois avec une dalle en verre",
    },
    {
      titre:       "Meuble TV en bois",
      description: "",
      type:        "Mobilier",
      src: "assets/images/meuble_tv.webp",
      alt: "Meuble TV en bois",
    },
    {
      titre:       "Aménagement de chambre",
      description: "",
      type:        "Rénovation",
      src: "assets/images/maison.webp",
      alt: "Aménagement de chambre",
    },
    {
      titre:       "Porte d'entrée bois massif",
      description: "Menuiserie sur-mesure & Encadrement pierre",
      type:        "Menuiserie",
      src: "assets/images/porte_entree_bois.webp",
      alt: "Porte d'entrée en bois massif encadrée de pierre de taille",
    },
    {
      titre:       "Escalier bois & garde-corps métal",
      description: "Bois massif & Ferronnerie sur-mesure",
      type:        "Menuiserie",
      src: "assets/images/escalier_bois_garde_corps.webp",
      alt: "Escalier intérieur en bois avec garde-corps en barreaux métalliques noirs",
    },
    {
      titre:       "Rénovation maison ancienne",
      description: "Parquet chêne & Mise en valeur murs en pierre",
      type:        "Rénovation",
      src: "assets/images/renovation_interieure_pierre_parquet.webp",
      alt: "Rénovation intérieure d'une maison ancienne avec parquet clair et murs en pierre apparente",
    },
    {
      titre:       "Cuisine compacte & verrière",
      description: "Aménagement optimisé & Séparation verrière atelier",
      type:        "Cuisine",
      src: "assets/images/cuisine_compacte_verriere.webp",
      alt: "Cuisine compacte moderne avec verrière atelier noire et accès salle de bain",
    },
    {
      titre:       "Pose de parquet stratifié",
      description: "Finition soignée & Plinthes assorties",
      type:        "Rénovation",
      src: "assets/images/parquet_stratifie_cuisine.webp",
      alt: "Parquet stratifié teinte chêne clair posé dans une cuisine et couloir",
    },
    {
      titre:       "Cuisine bois & plan béton ciré",
      description: "Façades chêne sur-mesure & Crédence béton",
      type:        "Cuisine",
      src: "assets/images/cuisine_bois_plan_beton.webp",
      alt: "Cuisine en bois chêne avec plan de travail béton ciré et mur en pierre apparente",
    },
    {
      titre:       "Cuisine hêtre en angle",
      description: "Agencement en L & Plan de travail béton",
      type:        "Cuisine",
      src: "assets/images/cuisine_hetre_angle.webp",
      alt: "Cuisine d'angle en hêtre clair avec hotte inox et électroménager encastré",
    },
    {
      titre:       "Meuble vasque travertin",
      description: "Plan travertin & Caisson suspendu sur-mesure",
      type:        "Pièces d'eau",
      src: "assets/images/meuble_vasque_travertin.webp",
      alt: "Meuble vasque suspendu avec plan en travertin et mur en pavés de verre",
    },
    {
      titre:       "Douche à l'italienne carrelage pierre",
      description: "Carrelage grand format & Paroi verre fixe",
      type:        "Pièces d'eau",
      src: "assets/images/douche_italienne_grise.webp",
      alt: "Douche à l'italienne carrelée façon pierre grise avec paroi en verre",
    },
    {
      titre:       "Cabine de douche blanche",
      description: "Receveur compact & Portes battantes verre",
      type:        "Pièces d'eau",
      src: "assets/images/cabine_douche_blanche.webp",
      alt: "Cabine de douche blanche avec portes en verre et colonne de douche",
    },
    {
      titre:       "WC pierre & carreaux de ciment",
      description: "Mur en pierre apparente & Sol carreaux de ciment",
      type:        "Pièces d'eau",
      src: "assets/images/wc_pierre_carreaux_ciment.webp",
      alt: "Toilettes avec mur en pierre apparente et sol en carreaux de ciment à motifs",
    },
    {
      titre:       "Porte bois croix occitane",
      description: "Menuiserie sur-mesure & Sculpture sur bois",
      type:        "Menuiserie",
      src: "assets/images/porte_bois_croix_occitane.webp",
      alt: "Porte en bois massif ornée d'une croix occitane sculptée",
    },
    {
      titre:       "Fenêtre PVC petits carreaux",
      description: "Menuiserie PVC & Vitrage à petits carreaux",
      type:        "Menuiserie",
      src: "assets/images/fenetre_pvc_petits_carreaux.webp",
      alt: "Fenêtre PVC à deux vantaux et petits carreaux",
    },
    {
      titre:       "Fenêtre alu & vue jardin",
      description: "Menuiserie aluminium & Encadrement pierre",
      type:        "Menuiserie",
      src: "assets/images/fenetre_alu_vue_jardin.webp",
      alt: "Fenêtre aluminium noire posée dans un mur en pierre avec vue sur le jardin",
    },
    {
      titre:       "Chambre fenêtre bois & poutres",
      description: "Menuiserie bois & Poutres apparentes",
      type:        "Menuiserie",
      src: "assets/images/chambre_fenetre_bois_poutres.webp",
      alt: "Chambre avec fenêtre bois sur-mesure, poutres apparentes et étagère en bois",
    },
    {
      titre:       "Cloison vitrée de bureau",
      description: "Séparation aluminium & Verre dépoli",
      type:        "Menuiserie",
      src: "assets/images/cloison_vitree_bureau.webp",
      alt: "Cloison vitrée de bureau avec porte coulissante en verre dépoli",
    },
    {
      titre:       "Verrière atelier blanche",
      description: "Séparation sur-mesure & Style atelier",
      type:        "Menuiserie",
      src: "assets/images/verriere_atelier_blanche.webp",
      alt: "Verrière atelier blanche avec soubassement séparant deux pièces",
    },
    {
      titre:       "Mezzanine garde-corps verre",
      description: "Garde-corps verre & Structure bois",
      type:        "Menuiserie",
      src: "assets/images/mezzanine_verriere_garde_corps.webp",
      alt: "Mezzanine avec garde-corps en verre et structure bois laqué blanc",
    },
    {
      titre:       "Placard coulissant & miroir",
      description: "Portes coulissantes & Façade miroir",
      type:        "Mobilier",
      src: "assets/images/placard_coulissant_miroir.webp",
      alt: "Grand placard sur-mesure avec portes coulissantes blanches et miroir",
    },
    {
      titre:       "Buffet chêne massif",
      description: "Bois chêne massif & Tiroirs et portes",
      type:        "Mobilier",
      src: "assets/images/buffet_chene_massif.webp",
      alt: "Buffet bas en chêne massif avec tiroirs et portes à panneaux",
    },
    {
      titre:       "Table basse bois & tiroir",
      description: "Plateau bois & Piétement laqué",
      type:        "Mobilier",
      src: "assets/images/table_basse_bois_tiroir.webp",
      alt: "Table basse en bois avec tiroir central, piétement laqué blanc et tablette",
    },
    {
      titre:       "Séjour lambris & bar pierre",
      description: "Lambris bois clair & Bar en pierre",
      type:        "Rénovation",
      src: "assets/images/sejour_lambris_bar_pierre.webp",
      alt: "Séjour avec lambris bois clair, poutres apparentes et bar en pierre",
    },
    {
      titre:       "Séjour pierre & poêle",
      description: "Béton ciré & Mise en valeur pierre",
      type:        "Rénovation",
      src: "assets/images/sejour_pierre_poutres_poele.webp",
      alt: "Séjour rénové avec murs en béton ciré, pierre apparente, poutres et poêle",
    },
    {
      titre:       "Chambre lambris blanc",
      description: "Lambris bois & Finition blanche",
      type:        "Rénovation",
      src: "assets/images/chambre_lambris_blanc.webp",
      alt: "Chambre habillée de lambris bois blanc avec applique murale",
    },
    {
      titre:       "Tête de lit en lambris",
      description: "Lambris bois & Éclairage intégré",
      type:        "Rénovation",
      src: "assets/images/chambre_lambris_applique.webp",
      alt: "Mur de chambre en lambris bois blanc avec applique allumée",
    },
    {
      titre:       "Charpente & poutres blanchies",
      description: "Poutres anciennes & Finition chaulée",
      type:        "Rénovation",
      src: "assets/images/charpente_poutres_blanches.webp",
      alt: "Charpente avec poutres anciennes blanchies sous plafond clair",
    },
    {
      titre:       "Poutres anciennes & lustre",
      description: "Mise en valeur poutres & Plafond clair",
      type:        "Rénovation",
      src: "assets/images/poutres_anciennes_lustre.webp",
      alt: "Poutres anciennes apparentes au plafond avec lustre en cristal doré",
    },
    {
      titre:       "Rosace plafond & lustre",
      description: "Rosace décorative & Pose de lustre",
      type:        "Rénovation",
      src: "assets/images/rosace_plafond_lustre.webp",
      alt: "Rosace de plafond décorative avec lustre en cristal",
    },
    {
      titre:       "Arche pierre & parquet ancien",
      description: "Arche en pierre & Parquet massif restauré",
      type:        "Rénovation",
      src: "assets/images/arche_pierre_parquet_ancien.webp",
      alt: "Pièce avec arche en pierre apparente et parquet massif ancien restauré",
    },
    {
      titre:       "Transition parquet & pierre",
      description: "Pose parquet & Conservation sol pierre",
      type:        "Rénovation",
      src: "assets/images/transition_parquet_pierre.webp",
      alt: "Transition entre un parquet contemporain et un ancien sol en pierre",
    },
    {
      titre:       "Parquet stratifié & escalier",
      description: "Pose stratifié & Finition couloir",
      type:        "Rénovation",
      src: "assets/images/parquet_stratifie_couloir.webp",
      alt: "Parquet stratifié chêne clair posé dans un couloir près d'un escalier bois",
    },
  ],
  carte: {
  lat:    44.4547,
  lng:    2.6244,
  rayon:  50000,
  label:  "Bezonnes"
  },
};
